version: '3'

volumes:
  foodgram_pg_data_production:
  foodgram_static_volume:
  foodgram_media_files:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - foodgram_pg_data_production:/var/lib/postgresql/data
  backend:
    image: slavakulikov/foodgram_backend
    env_file: ../.env
    volumes:
      - foodgram_static_volume:/backend_static
      - foodgram_media_files:/media
      - ../data:/app/foodgram_data
  frontend:
    image: slavakulikov/foodgram_frontend
    env_file: ../.env
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static_volume:/static
  nginx:
    image: slavakulikov/foodgram_gateway
    env_file: ../.env
    ports:
      - 9090:80
    volumes:
      - foodgram_static_volume:/static
      - foodgram_media_files:/media
