version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django_user  -d django" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    build: ../backend/
    volumes:
      - static:/backend_static
      - media:/media

    env_file:
      - ../.env
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        cp -r /app/collected_static/. /backend_static/static/ &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/api/recipes/" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    container_name: foodgram-front
    env_file:
      - ../.env
    build: ../frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    container_name: foodgram-nginx
    build: ../nginx/
    env_file:
      - ../.env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      backend:
        condition: service_healthy