# Generated by Django 4.2.20 on 2025-06-25 10:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_favorite_recipe_alter_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата публикации",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=core.fields.FromOneSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=core.fields.FromOneSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Название тега"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"), name="unique_ingredient"
            ),
        ),
    ]
