# Generated by Django 4.2.20 on 2025-06-25 16:49

import django.core.validators
from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_options_recipe_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=core.fields.FromOneSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=core.fields.FromOneSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
