# Generated by Django 4.2.20 on 2025-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": 'объект "Подписка"',
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/",
                verbose_name="Аватар"),
        ),
    ]
