# Generated by Django 4.2.20 on 2025-06-21 16:59

from django.db import migrations

import core.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_subscription_author_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.managers.UserManager()),
            ],
        ),
    ]
